coins:
  - symbol: "SOL/USDT"
    exchange: "binance"
  - symbol: "ADA/USDT"
    exchange: "binance"
  - symbol: "CAKE/USDT"
    exchange: "binance"
  - symbol: "SEI/USDT"
    exchange: "binance"
  - symbol: "HBAR/USDT"
    exchange: "binance"
  - symbol: "WLD/USDT"
    exchange: "binance"
  - symbol: "PEPE/USDT"
    exchange: "binance"
  - symbol: "DOGE/USDT"
    exchange: "binance"
  - symbol: "RAY/USDT"
    exchange: "binance"
  - symbol: "DOT/USDT"
    exchange: "binance"
  - symbol: "MATIC/USDT"
    exchange: "binance"

csv_file_path: "data/combined_crypto_data.csv"
output_dir: "analysis_results"  # Directory for analysis output files
start_date: "2017-01-01"
end_date: "now"
